# Generated by Django 3.2.5 on 2021-07-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teste',
            old_name='idade',
            new_name='idade_pessoa',
        ),
    ]
