# Generated by Django 3.2.5 on 2021-07-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_idade_teste_idade_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
